name: test_env
channels:
 - bioconda
 - defaults
 - agbiome
dependencies:
 - fastqc
 - multiqc
 - gffread
 - kallisto
 - samtools
 - rseqc
 - qualimap
 - bedtools
 - bedops
 - hisat2
 - stringtie
 - salmon
 - bbtools
